---
# tasks file for openfaas
- name: Install git
  become: True
  package:
    name: git
    state: present

- name: Check openfaas instalation
  shell: "docker service ls | grep 'func_'"
  ignore_errors: True
  register: openfaas_installed

- name: Install openfaas
  shell: "git clone https://github.com/openfaas/faas && cd faas && ./deploy_stack.armhf.sh --no-auth"
  when: openfaas_installed.rc != 0

- name: Cleanup openfaas install
  file:
    path: /home/pi/faas
    state: absent

- name: Install openfaas-rabbitmq-connector
  docker_service:
        project_name: openfaas-rabbitmq-connector
        state: present
        definition:
                version: '2'
                services:
                        connector:
                                image: mcostea/rabbitmq-openfaas-connector
                                environment:
                                        MQ_TOPICS: "{{ openfaas_connector_topics }}"
                                        MQ_HOST: "{{ openfaas_connector_mq_host }}"
                                        MQ_PORT: "{{ openfaas_connector_mq_port }}"
                                        FAAS_GW_URL: "{{ openfaas_connector_faas_gw_url }}"
                                networks:
                                        - func_functions
                networks:
                        func_functions:
                                external: true
  register: output
- debug:
        var: output
