---
# tasks file for openfaas
- name: Install git
  become: True
  package:
    name: git
    state: present

- name: Check openfaas instalation
  shell: "docker service ls | grep 'func_'"
  register: openfaas_installed

- name: Install openfaas
  shell: "git clone https://github.com/openfaas/faas && cd faas && ./deploy_stack.sh --no-auth"
  when: openfaas_installed.rc != 0

- name: Check if openfaas-rabbitmq-connector is installed
  shell: "docker service ls | grep 'connector'"
  ignore_errors: True
  register: openfaas_rabbit_connector_installed

- name: Install openfaas-rabbitmq-connector
  shell: "docker service create --name connector -e MQ_TOPICS={{ openfaas_connector_topics }} -e MQ_HOST={{ openfaas_connector_mq_host  }} -e MQ_PORT={{ openfaas_connector_mq_port  }} -e FAAS_GW_URL={{ openfaas_connector_faas_gw_url }} --network func_functions templum/rabbitmq-connector"
  when: openfaas_rabbit_connector_installed.rc != 0

