---
# tasks file for rabbitmq

- name: Install rabbitmq
  docker_container:
          name: rabbitmq
          image: mcostea/rabbitmq
          pull: yes
          ports:
                  - "5672:5672"
                  - "5671:5671"
                  - "15672:15672"
                  - "1883:1883"
                  - "8883:8883"
          state: started
