---
- name: Install python dependencies
  become: yes
  package:
    name="{{ item }}"
    state=present
  with_items:
    - python-apt
    - python-pip

- name: Check if Docker is already installed
  shell: dpkg-query -W docker-ce
  ignore_errors: True
  register: docker_check

- name: Download docker install script
  get_url:
    url: https://get.docker.com
    dest: /tmp/docker-install.sh
    mode: "a+x"
  when: docker_check is failed

- name: Run install script
  shell: /bin/sh /tmp/docker-install.sh
  when: docker_check is failed

- name: Remove temporary file
  file:
    path: /tmp/docker-install.sh
    state: absent
  when: docker_check is failed
    
- name: Set Docker to auto-start
  service: name=docker enabled=true state=started

- name: Add docker_pi_group_users to the docker group
  become: yes
  user:
    name: "{{ item }}"
    groups: docker
  with_items:
    - pi

- name: Login to docker hub
  command: docker login --username="{{ docker_pi_hub_username }}" --password="{{ docker_pi_hub_password }}"
  become_user: "{{ docker_pi_user }}"
  when: docker_pi_hub_username != "" and docker_pi_hub_password != ""

- name: Install docker-py
  pip:
    name: docker-py
    state: present
